import { Download, FileText, LockKeyhole, Printer, Sparkles } from "lucide-react";
import { useParams } from "react-router-dom";

import {
  useGeneratePrd,
  useWorkspace,
} from "@/features/discovery/queries";
import type { PrdSection } from "@/types/workspace";

function fileSlug(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "product"
  );
}

function buildPrdMarkdown(projectName: string, sections: PrdSection[]): string {
  const lines = [
    `# ${projectName}`,
    "",
    "_Product requirements document_",
    "",
  ];

  for (const section of sections) {
    lines.push(`## ${section.title}`, "", section.body.trim(), "");
  }

  return `${lines.join("\n").trim()}\n`;
}

function downloadMarkdown(projectName: string, sections: PrdSection[]) {
  const blob = new Blob([buildPrdMarkdown(projectName, sections)], {
    type: "text/markdown;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `${fileSlug(projectName)}-prd.md`;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function printPrd(projectName: string, sections: PrdSection[]) {
  const printWindow = window.open("", "_blank");

  if (!printWindow) {
    window.alert(
      "The print window was blocked. Allow pop-ups for Architect and try again.",
    );
    return;
  }

  printWindow.opener = null;
  const renderedSections = sections
    .map(
      (section) => `
        <section>
          <h2>${escapeHtml(section.title)}</h2>
          <div class="section-body">${escapeHtml(section.body)}</div>
        </section>
      `,
    )
    .join("");

  printWindow.document.open();
  printWindow.document.write(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(projectName)} - PRD</title>
    <style>
      @page { size: A4; margin: 18mm; }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        color: #171717;
        font-family: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        font-size: 10.5pt;
        line-height: 1.65;
      }
      header { margin-bottom: 30px; padding-bottom: 18px; border-bottom: 1px solid #e5e5e5; }
      .eyebrow { margin: 0 0 8px; color: #737373; font-size: 8pt; font-weight: 700; letter-spacing: .14em; text-transform: uppercase; }
      h1 { margin: 0; font-size: 26pt; line-height: 1.2; letter-spacing: -.03em; }
      .subtitle { margin: 10px 0 0; color: #737373; font-size: 9pt; }
      section { margin: 0 0 24px; }
      h2 { margin: 0 0 8px; font-size: 15pt; line-height: 1.35; break-after: avoid-page; }
      .section-body { white-space: pre-wrap; overflow-wrap: anywhere; }
      @media screen {
        body { max-width: 800px; margin: 36px auto; padding: 0 28px; }
      }
    </style>
  </head>
  <body>
    <header>
      <p class="eyebrow">Product requirements document</p>
      <h1>${escapeHtml(projectName)}</h1>
      <p class="subtitle">Generated by Architect</p>
    </header>
    ${renderedSections}
  </body>
</html>`);
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
}

export function PrdPage() {
  const { projectId = "" } = useParams();
  const { data: workspace } = useWorkspace(projectId);
  const generatePrd = useGeneratePrd(projectId);

  if (!workspace) return null;

  if (workspace.prd.status === "generating") {
    return (
      <div className="grid h-full place-items-center p-8">
        <div className="max-w-md text-center">
          <span className="mx-auto mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-violet-50 text-violet-600">
            <Sparkles size={19} />
          </span>
          <p className="eyebrow mb-2">PRD</p>
          <h2 className="text-xl font-semibold">Generation needs to finish</h2>
          <p className="mt-2 text-sm leading-6 text-neutral-500">
            Founder approval is already saved. Resume the verified compilation
            without replaying the confirmation turn.
          </p>
          {generatePrd.isError && (
            <p className="mt-3 text-sm text-red-700">
              {generatePrd.error instanceof Error
                ? generatePrd.error.message
                : "PRD generation failed."}
            </p>
          )}
          <button
            type="button"
            disabled={generatePrd.isPending}
            onClick={() => generatePrd.mutate()}
            className="mt-5 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-40"
          >
            {generatePrd.isPending ? "Generating…" : "Resume PRD generation"}
          </button>
        </div>
      </div>
    );
  }

  if (workspace.prd.status !== "ready") {
    return (
      <div className="grid h-full place-items-center p-8">
        <div className="max-w-md text-center">
          <span className="mx-auto mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-neutral-100 text-neutral-500">
            <LockKeyhole size={19} />
          </span>
          <p className="eyebrow mb-2">PRD</p>
          <h2 className="text-xl font-semibold">Not generated yet</h2>
          <p className="mt-2 text-sm leading-6 text-neutral-500">
            Architect will first decide that discovery is sufficiently covered.
            You still make the final decision to generate the PRD.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto p-6 md:p-10">
      <article className="mx-auto max-w-4xl">
        <div className="mb-10 flex flex-wrap items-start justify-between gap-6">
          <div>
            <div className="mb-3 flex items-center gap-2 text-neutral-400">
              <FileText size={16} />
              <span className="eyebrow">Product requirements document</span>
            </div>
            <h1 className="text-3xl font-semibold tracking-tight">
              {workspace.project.name}
            </h1>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={() =>
                downloadMarkdown(workspace.project.name, workspace.prd.sections)
              }
              className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-3.5 py-2.5 text-sm font-medium text-white transition hover:bg-neutral-800"
              title="Download this PRD as a Markdown file"
            >
              <Download size={15} />
              Download PRD
            </button>
            <button
              type="button"
              onClick={() => printPrd(workspace.project.name, workspace.prd.sections)}
              className="inline-flex items-center gap-2 rounded-xl border border-black/10 bg-white px-3.5 py-2.5 text-sm font-medium text-neutral-700 transition hover:bg-neutral-50 hover:text-neutral-950"
              title="Print this PRD or save it as a PDF"
            >
              <Printer size={15} />
              Save as PDF
            </button>
            <span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-700">
              <Sparkles size={13} />
              Generated
            </span>
          </div>
        </div>

        <div className="space-y-8">
          {workspace.prd.sections.map((section) => (
            <section key={section.id} className="surface p-6">
              <h2 className="mb-3 text-lg font-semibold">{section.title}</h2>
              <p className="whitespace-pre-wrap text-sm leading-7 text-neutral-600">
                {section.body}
              </p>
            </section>
          ))}
        </div>
      </article>
    </div>
  );
}
